import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [cardNumber, setCardNumber] = useState("4111111111111111");
  const [cardExpiry, setCardExpiry] = useState("01/20");
  const [securityCode, setSecurityCode] = useState("123");
  const [token, setToken] = useState<string | null>(null);

  const handleCreateToken = async () => {
    const { data } = await axios.post("https://api.veritrans.co.jp/4gtoken", {
      card_number: cardNumber,
      card_expire: cardExpiry,
      security_code: securityCode,
      token_api_key: 'cd76ca65-7f54-4dec-8ba3-11c12e36a548',
    });
    setToken(data.token);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <input placeholder="カード番号" type="text" value={cardNumber} onChange={(e) => setCardNumber(e.target.value)} />
          <input placeholder="有効期限" type="text" value={cardExpiry} onChange={(e) => setCardExpiry(e.target.value)} />
          <input placeholder="セキュリティーコード" type="text" value={securityCode} onChange={(e) => setSecurityCode(e.target.value)} />
          <button onClick={handleCreateToken}>Create Token</button>
          <div>Result: {token}</div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
